# Generated by Django 3.0.8 on 2020-07-17 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='khachhang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(max_length=255)),
                ('address_kh', models.CharField(max_length=255)),
                ('phone_kh', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nhanvien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nv', models.CharField(max_length=100)),
                ('name_nv', models.CharField(max_length=255)),
                ('age_nv', models.IntegerField()),
                ('address_nv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pro', models.CharField(max_length=255)),
                ('price_pro', models.IntegerField()),
                ('description', models.TextField()),
                ('id_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='khachhang',
            name='id_kh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.nhanvien'),
        ),
    ]
